//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rep.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Components {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Components() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rep.Resources.Text.Components", typeof(Components).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   are you ready? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogCaptionConfirm {
            get {
                return ResourceManager.GetString("DialogCaptionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogCaptionFailure {
            get {
                return ResourceManager.GetString("DialogCaptionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   results! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogCaptionResult {
            get {
                return ResourceManager.GetString("DialogCaptionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   succeeded! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogCaptionSucceeded {
            get {
                return ResourceManager.GetString("DialogCaptionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   warning! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogCaptionWarning {
            get {
                return ResourceManager.GetString("DialogCaptionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .cs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringCSFileExtension {
            get {
                return ResourceManager.GetString("StringCSFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;log4net&gt;
        ///    &lt;!-- NORMAL LOG --&gt;
        ///    &lt;appender name=&quot;OperationLogAppender&quot; type=&quot;log4net.Appender.RollingFileAppender&quot;&gt;
        ///      &lt;param name=&quot;RollingStyle&quot; value=&quot;date&quot; /&gt;
        ///      &lt;param name=&quot;File&quot; value=&quot;{0}\logs\log&quot; /&gt;
        ///      &lt;param name=&quot;DatePattern&quot; value=&apos;&quot;_&quot;yyyyMMdd&quot;.log&quot;&apos; /&gt;
        ///      &lt;param name=&quot;StaticLogFileName&quot; value=&quot;false&quot; /&gt;
        ///      &lt;param name=&quot;AppendToFile&quot; value=&quot;true&quot; /&gt;
        ///      &lt;filter type=&quot;log4net.Filter.LevelRangeFilter&quot;&gt;
        ///       [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StringLog4NetConfigXml {
            get {
                return ResourceManager.GetString("StringLog4NetConfigXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   myanoshi0626@gmail.com に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextContact {
            get {
                return ResourceManager.GetString("TextContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;END&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextLogEnd {
            get {
                return ResourceManager.GetString("TextLogEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ----- REP END ----- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextLogEndRep {
            get {
                return ResourceManager.GetString("TextLogEndRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ------ INNER EXCEPTION ------ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextLogInnerExeptionHeader {
            get {
                return ResourceManager.GetString("TextLogInnerExeptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;START&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextLogStart {
            get {
                return ResourceManager.GetString("TextLogStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ----- REP START ----- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextLogStartRep {
            get {
                return ResourceManager.GetString("TextLogStartRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [FATAL BACKEND] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextLogTagBackendFatal {
            get {
                return ResourceManager.GetString("TextLogTagBackendFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [FATAL FRONTEND] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextLogTagFrontendFatal {
            get {
                return ResourceManager.GetString("TextLogTagFrontendFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [FATAL MAILER] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextLogTagMailerFatal {
            get {
                return ResourceManager.GetString("TextLogTagMailerFatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://github.com/yanosea/rep.git に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextRepositoryUrlForCommand {
            get {
                return ResourceManager.GetString("TextRepositoryUrlForCommand", resourceCulture);
            }
        }
    }
}
