//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rep.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Environments {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Environments() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rep.Resources.Text.Environments", typeof(Environments).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   .cache に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameCachedFiles {
            get {
                return ResourceManager.GetString("DirNameCachedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   closing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameClosing {
            get {
                return ResourceManager.GetString("DirNameClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   config に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameConfig {
            get {
                return ResourceManager.GetString("DirNameConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   daily に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameDaily {
            get {
                return ResourceManager.GetString("DirNameDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   dest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameDestConfig {
            get {
                return ResourceManager.GetString("DirNameDestConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   errorlogs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameErrorLog {
            get {
                return ResourceManager.GetString("DirNameErrorLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rep に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameGit {
            get {
                return ResourceManager.GetString("DirNameGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .git に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameGitHidden {
            get {
                return ResourceManager.GetString("DirNameGitHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   logs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameLog {
            get {
                return ResourceManager.GetString("DirNameLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   monthly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameMonthly {
            get {
                return ResourceManager.GetString("DirNameMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   opening に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameOpening {
            get {
                return ResourceManager.GetString("DirNameOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rep に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameRep {
            get {
                return ResourceManager.GetString("DirNameRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rep-installer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameRepInstaller {
            get {
                return ResourceManager.GetString("DirNameRepInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   reports に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameReport {
            get {
                return ResourceManager.GetString("DirNameReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   report に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameReportConfig {
            get {
                return ResourceManager.GetString("DirNameReportConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   weekly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirNameWeekly {
            get {
                return ResourceManager.GetString("DirNameWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .cred.toml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameCredentialConfig {
            get {
                return ResourceManager.GetString("FileNameCredentialConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   daily_conf.toml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameDailyConfig {
            get {
                return ResourceManager.GetString("FileNameDailyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   daily_dest_conf.toml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameDailyDestConfig {
            get {
                return ResourceManager.GetString("FileNameDailyDestConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   log_conf.toml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameLogConfig {
            get {
                return ResourceManager.GetString("FileNameLogConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   monthly_conf.toml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameMonthlyConfig {
            get {
                return ResourceManager.GetString("FileNameMonthlyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   monthly_dest_conf.toml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameMonthlyDestConfig {
            get {
                return ResourceManager.GetString("FileNameMonthlyDestConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   preferences.toml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNamePreferencesConfig {
            get {
                return ResourceManager.GetString("FileNamePreferencesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rep-installer.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameRepInstaller {
            get {
                return ResourceManager.GetString("FileNameRepInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   reports.db に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameSQLiteDB {
            get {
                return ResourceManager.GetString("FileNameSQLiteDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   weekly_conf.toml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameWeeklyConfig {
            get {
                return ResourceManager.GetString("FileNameWeeklyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   weekly_dest_conf.toml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameWeeklyDestConfig {
            get {
                return ResourceManager.GetString("FileNameWeeklyDestConfig", resourceCulture);
            }
        }
    }
}
