//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rep.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Formats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Formats() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rep.Resources.Text.Formats", typeof(Formats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [ {0} ] {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   COMMAND LINE ARGS : [ {0} ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogCommandLineArguments {
            get {
                return ResourceManager.GetString("LogCommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REP CURRENT VERSION : [ {0} ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogCurrentVersion {
            get {
                return ResourceManager.GetString("LogCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   REP LATEST VERSION : [ {0} ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogLatestVersion {
            get {
                return ResourceManager.GetString("LogLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ATTACHED : [ {0} ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogSentAttachmentsFormat {
            get {
                return ResourceManager.GetString("LogSentAttachmentsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SENT BCC : [ {0} : {1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogSentBccFormat {
            get {
                return ResourceManager.GetString("LogSentBccFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SENT CC : [ {0} : {1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogSentCcFormat {
            get {
                return ResourceManager.GetString("LogSentCcFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SENT TO : [ {0} : {1}] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogSentToFormat {
            get {
                return ResourceManager.GetString("LogSentToFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SUCCESS AUTHENTICATING : [ {0} ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogSuccessAuthenticatingFormat {
            get {
                return ResourceManager.GetString("LogSuccessAuthenticatingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONNECTION ESTABLISHED : [ {0} : {1} ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogSuccessConnectingFormat {
            get {
                return ResourceManager.GetString("LogSuccessConnectingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SUCCESS DISCONNECTING : [ {0} : {1} ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogSuccessDisconnectingFormat {
            get {
                return ResourceManager.GetString("LogSuccessDisconnectingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SUCCESS SENDING : [ {0} ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogSuccessSendingFormat {
            get {
                return ResourceManager.GetString("LogSuccessSendingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} :: {1} Line #{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogTag {
            get {
                return ResourceManager.GetString("LogTag", resourceCulture);
            }
        }
    }
}
