//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rep.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rep.Resources.Text.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   CANCEL SENDING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelSending {
            get {
                return ResourceManager.GetString("CancelSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CHECK UPDATES に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckUpdates {
            get {
                return ResourceManager.GetString("CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EXECUTE UPDATE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExecuteUpdate {
            get {
                return ResourceManager.GetString("ExecuteUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED AUTHENTICATING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureAuthenticating {
            get {
                return ResourceManager.GetString("FailureAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED CONNECTING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureConnecting {
            get {
                return ResourceManager.GetString("FailureConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED DAILY IS NOT PREPARED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureDailyNotPrepared {
            get {
                return ResourceManager.GetString("FailureDailyNotPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED DISCONNECTING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureDisconnecting {
            get {
                return ResourceManager.GetString("FailureDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED GETTING COMMAND LINE ARGUMENTS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureGettingCommandLineArguments {
            get {
                return ResourceManager.GetString("FailureGettingCommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED GETTING THRESHOLD TIME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureGettingThresholdTime {
            get {
                return ResourceManager.GetString("FailureGettingThresholdTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED GETTING TODAY&apos;S OPENING TIME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureGettingTodaysOpeningTime {
            get {
                return ResourceManager.GetString("FailureGettingTodaysOpeningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED GIT COMMAND : [ {0} ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureGitCommand {
            get {
                return ResourceManager.GetString("FailureGitCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED INITIALIZING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureInitializing {
            get {
                return ResourceManager.GetString("FailureInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED INVALID PARAM INPUT : [ {0} ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureInputtingAbnormalParam {
            get {
                return ResourceManager.GetString("FailureInputtingAbnormalParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED INVALID TIME INPUT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureInputtingAbnormalTime {
            get {
                return ResourceManager.GetString("FailureInputtingAbnormalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED NONE OF THE MONTHLY FILES ARE SELECTE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureNoneOfMonthlyFilesSelected {
            get {
                return ResourceManager.GetString("FailureNoneOfMonthlyFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED NONE OF THE REPORT ARE SELECTED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureNoneOfReportSelected {
            get {
                return ResourceManager.GetString("FailureNoneOfReportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED NONE OF THE WEEKLY FILES ARE SELECTE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureNoneOfWeeklyFilesSelected {
            get {
                return ResourceManager.GetString("FailureNoneOfWeeklyFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED READING CONFIG FILES に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureReadingConfigFiles {
            get {
                return ResourceManager.GetString("FailureReadingConfigFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED SAVING CONFIG に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureSavingConfig {
            get {
                return ResourceManager.GetString("FailureSavingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED SENDING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureSending {
            get {
                return ResourceManager.GetString("FailureSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAILED SENDING REPORTS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureSendingReport {
            get {
                return ResourceManager.GetString("FailureSendingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SOMETHING WRONG OCCURED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureSomethingWrongOccured {
            get {
                return ResourceManager.GetString("FailureSomethingWrongOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SKIP TOP PAGE ENABLE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SkipTopPageEnable {
            get {
                return ResourceManager.GetString("SkipTopPageEnable", resourceCulture);
            }
        }
    }
}
