//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rep.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rep.Resources.Text.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   send...
        ///
        ///{0}
        ///are you sure? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmSendingMessage {
            get {
                return ResourceManager.GetString("ConfirmSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   send...
        ///
        ///{0}
        ///are you sure?
        ///
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmSendingMessageWithClosing {
            get {
                return ResourceManager.GetString("ConfirmSendingMessageWithClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rep you using is v{0} . it&apos;s available {1} !
        ///do you want to update to {1} ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmUpdatingRep {
            get {
                return ResourceManager.GetString("ConfirmUpdatingRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed  getting threshold time... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureGettingThresholdTime {
            get {
                return ResourceManager.GetString("FailureGettingThresholdTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed  getting today&apos;s opening time... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureGettingTodaysOpeningTime {
            get {
                return ResourceManager.GetString("FailureGettingTodaysOpeningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed initializing,,, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureInitializing {
            get {
                return ResourceManager.GetString("FailureInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ {0} ] is invalid... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureInputtingAbnormalParam {
            get {
                return ResourceManager.GetString("FailureInputtingAbnormalParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   invalid time input... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureInputtingAbnormalTime {
            get {
                return ResourceManager.GetString("FailureInputtingAbnormalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ {0} ] was failed to send... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureResultMessage {
            get {
                return ResourceManager.GetString("FailureResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed saving config... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureSavingConfig {
            get {
                return ResourceManager.GetString("FailureSavingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   failed sending reports... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureSendingReport {
            get {
                return ResourceManager.GetString("FailureSendingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   something wrong occured... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailureSomethingWrongOccured {
            get {
                return ResourceManager.GetString("FailureSomethingWrongOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   saved config! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SucceedSavingConfig {
            get {
                return ResourceManager.GetString("SucceedSavingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   send reports! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SucceedSendingReport {
            get {
                return ResourceManager.GetString("SucceedSendingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ {0} ] was sent successfully! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuccessResultMessage {
            get {
                return ResourceManager.GetString("SuccessResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   press calc button! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningDailyNotPrepared {
            get {
                return ResourceManager.GetString("WarningDailyNotPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   none of the monthly files are selected... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningNoneOfMonthlyFilesSelected {
            get {
                return ResourceManager.GetString("WarningNoneOfMonthlyFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   none of the report are selected... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningNoneOfReportSelected {
            get {
                return ResourceManager.GetString("WarningNoneOfReportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   none of the weekly files are selected... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WarningNoneOfWeeklyFilesSelected {
            get {
                return ResourceManager.GetString("WarningNoneOfWeeklyFilesSelected", resourceCulture);
            }
        }
    }
}
