//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rep.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Pages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rep.Resources.Text.Pages", typeof(Pages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   credential に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameConfigCredential {
            get {
                return ResourceManager.GetString("NameConfigCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   daily に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameConfigDaily {
            get {
                return ResourceManager.GetString("NameConfigDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   monthly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameConfigMonthly {
            get {
                return ResourceManager.GetString("NameConfigMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   preferences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameConfigPreferences {
            get {
                return ResourceManager.GetString("NameConfigPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   weekly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameConfigWeekly {
            get {
                return ResourceManager.GetString("NameConfigWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   daily に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameReadDaily {
            get {
                return ResourceManager.GetString("NameReadDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   monthly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameReadMonthly {
            get {
                return ResourceManager.GetString("NameReadMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   weekly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameReadWeekly {
            get {
                return ResourceManager.GetString("NameReadWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   daily に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameWriteDaily {
            get {
                return ResourceManager.GetString("NameWriteDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   monthly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameWriteMonthly {
            get {
                return ResourceManager.GetString("NameWriteMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   weekly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NameWriteWeekly {
            get {
                return ResourceManager.GetString("NameWriteWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   config/credential に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathConfigCredential {
            get {
                return ResourceManager.GetString("PathConfigCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   config/daily に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathConfigDaily {
            get {
                return ResourceManager.GetString("PathConfigDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   config/monthly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathConfigMonthly {
            get {
                return ResourceManager.GetString("PathConfigMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   config/preferences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathConfigPreferences {
            get {
                return ResourceManager.GetString("PathConfigPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   config/weekly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathConfigWeekly {
            get {
                return ResourceManager.GetString("PathConfigWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   read/daily に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathReadDaily {
            get {
                return ResourceManager.GetString("PathReadDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   read/monthly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathReadMonthly {
            get {
                return ResourceManager.GetString("PathReadMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   read/weekly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathReadWeekly {
            get {
                return ResourceManager.GetString("PathReadWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   write/daily に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathWriteDaily {
            get {
                return ResourceManager.GetString("PathWriteDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   write/monthly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathWriteMonthly {
            get {
                return ResourceManager.GetString("PathWriteMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   write/weekly に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathWriteWeekly {
            get {
                return ResourceManager.GetString("PathWriteWeekly", resourceCulture);
            }
        }
    }
}
